In [19]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler,MinMaxScaler,OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.impute import SimpleImputer
from sklearn.feature_selection import SelectKBest,f_regression
from sklearn.decomposition import PCA

In [2]:
df = pd.read_csv('auto-mpg.csv')
df

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,car name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino
...,...,...,...,...,...,...,...,...,...
393,27.0,4,140.0,86,2790,15.6,82,1,ford mustang gl
394,44.0,4,97.0,52,2130,24.6,82,2,vw pickup
395,32.0,4,135.0,84,2295,11.6,82,1,dodge rampage
396,28.0,4,120.0,79,2625,18.6,82,1,ford ranger
397,31.0,4,119.0,82,2720,19.4,82,1,chevy s-10

In [3]:
print(df.dtypes)

mpg             float64
cylinders         int64
displacement    float64
horsepower          str
weight            int64
acceleration    float64
model year        int64
origin            int64
car name            str
dtype: object

In [4]:
df.select_dtypes(include=np.number).columns

Index(['mpg', 'cylinders', 'displacement', 'weight', 'acceleration',
       'model year', 'origin'],
      dtype='str')

In [5]:
numeric_columns = df.select_dtypes(include=np.number).columns
print("Numberic Columns:",numeric_columns)

Numberic Columns: Index(['mpg', 'cylinders', 'displacement', 'weight', 'acceleration',
       'model year', 'origin'],
      dtype='str')

In [6]:
categorical_columns = df.select_dtypes(include='object').columns
print("Categorical Columns:",categorical_columns)

Categorical Columns: Index(['horsepower', 'car name'], dtype='str')

C:\Users\Arav\AppData\Local\Temp\ipykernel_15472\3386719851.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_columns = df.select_dtypes(include='object').columns

In [7]:
df["origin"]=df["origin"].astype("object")

In [8]:
print(df.isnull().sum())

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [9]:
df=df.replace("?",np.nan)
df.isnull().sum()

mpg             0
cylinders       0
displacement    0
horsepower      6
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [10]:
df['horsepower'] = pd.to_numeric(df['horsepower'])

In [11]:
df['horsepower'] = df['horsepower'].fillna(df['horsepower'].mean())

In [12]:
print(df.isnull().sum())

mpg             0
cylinders       0
displacement    0
horsepower      0
weight          0
acceleration    0
model year      0
origin          0
car name        0
dtype: int64

In [15]:
scaler=MinMaxScaler().set_output(transform="pandas")
scaled_df=scaler.fit_transform(df[numeric_columns])
scaled_df.head()

,mpg,cylinders,displacement,weight,acceleration,model year,origin
0,0.239362,1.0,0.617571,0.536150,0.238095,0.0,0.0
1,0.159574,1.0,0.728682,0.589736,0.208333,0.0,0.0
2,0.239362,1.0,0.645995,0.516870,0.178571,0.0,0.0
3,0.186170,1.0,0.609819,0.516019,0.238095,0.0,0.0
4,0.212766,1.0,0.604651,0.520556,0.148810,0.0,0.0

In [16]:
categorical_columns=["origin","car name"]

In [23]:
encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
).set_output(transform="pandas")

encoder_data = encoder.fit_transform(df[categorical_columns])

display(encoder_data.head())

,origin_1,origin_2,origin_3,car name_amc ambassador brougham,car name_amc ambassador dpl,car name_amc ambassador sst,car name_amc concord,car name_amc concord d/l,car name_amc concord dl,car name_amc concord dl 6,...,car name_volvo 145e (sw),car name_volvo 244dl,car name_volvo 245,car name_volvo 264gl,car name_volvo diesel,car name_vw dasher (diesel),car name_vw pickup,car name_vw rabbit,car name_vw rabbit c (diesel),car name_vw rabbit custom
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
X = df.drop("mpg",axis=1)
y=df["mpg"]

In [32]:
X_numeric = X.select_dtypes(include=np.number)
selector = SelectKBest(
    score_func=f_regression,
    k=3
).set_output(transform='pandas')

X_selected = selector.fit_transform(X_numeric,y)

print(X_selected.head())

   cylinders  displacement  weight
0          8         307.0    3504
1          8         350.0    3693
2          8         318.0    3436
3          8         304.0    3433
4          8         302.0    3449